apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    name: vault
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8200
    - name: backend
      port: 8201
  selector:
    app: vault
